# Nginx configuration

server {
    listen 80;
    server_name localhost;

    root /var/www/html/src/public;
    index index.php;

    # Обработка загруженных файлов
    location /uploads/ {
        try_files $uri =404;
    }

    # Обработка только index.php
    location = /index.php {
        fastcgi_pass php-fpm:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Блокировка прямого доступа к другим PHP файлам
    location ~ \.php$ {
        return 404;
    }

    # Основная маршрутизация
    location / {
        try_files $uri /index.php$is_args$args;
    }
}

